language: node_js

node_js:
   - "8"

sudo: required

after_deploy:
   - echo "done deploying"

deploy:
   provider: elasticbeanstalk
   region: "ap-south-1"
   app: "Docker"
   env: "Docker-env-1"
   bucket_name: "elasticbeanstalk-ap-south-1-671141137976"
   bucket_path: "Docker"
   on:
     branch : master

   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY


