sudo: required

services:
    - docker 


before_install:
      - docker build -t docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true  docker-react npm run test

deploy:
   provider: elasticbeanstalk
   region: "ap-south-1"
   app: "Docker"
   env: "Docker-env"
   bucket_name: "elasticbeanstalk-ap-south-1-671141137976"
   bucket_path: "elasticbeanstalk-ap-south-1-671141137976/resources/_runtime/_embedded_extensions/Docker"
   on:
     branch : master

   access_key_id: $AWS_ACCESS_KEY
   secret_access_key:
         secure: "$AWS_SECRET_KEY"

